export const GET_AND_CACHE_USER_START = 'GET_AND_CACHE_USER_START'
export const GET_AND_CACHE_USER_FINISH = 'GET_AND_CACHE_USER_FINISH'
export const GET_AND_CACHE_USER_FAILED = 'GET_AND_CACHE_USER_FAILED'
export const CACHE_USER = 'CACHE_USER'